language: objective-c
cache: cocoapods
osx_image: xcode7.3

notifications:
email: false
on_success: never
on_failure: never


before_install:
- gem install xcov --no-ri --no-rdoc --no-document
- gem update fastlane --no-ri --no-rdoc --no-document
- gem install aws-sdk
#- export PATH=$PATH:$HOME/.local/bin


before_script:
#- aws s3 cp s3://bucket-ios-certs/iosDeveloper.p12.enc fastlane/cert/
#- aws s3 cp s3://bucket-ios-certs/iosDistribution.p12.enc fastlane/cert/
- ruby travis/get_certs_from_s3.rb
- openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in fastlane/cert/iosDeveloper.p12.enc -d -a -out fastlane/cert/iosDeveloper.p12
- openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in fastlane/cert/iosDistribution.p12.enc -d -a -out fastlane/cert/iosDistribution.p12


script: travis/script.sh
after_success: travis/after_success_script.sh