require 'securerandom'

fastlane_version "1.97.2"

default_platform :ios

platform :ios do
before_all do
end

desc "Run tests"
lane :test do
scan(
scheme: "ShipTracked",
workspace: "ShipTracked.xcworkspace",
clean: true,
code_coverage: true,
skip_slack: true,
sdk: "iphonesimulator9.3"
)
end

desc "Calculate test code coverage score. Need to run test beforehand."
lane :report_test_coverage do
xcov(
workspace: "ShipTracked.xcworkspace",
scheme: "ShipTracked",
output_directory: "xcov_output"
)
end

desc "Run Build"
lane :build do
create_keychain(
name: ENV["KEYCHAIN_NAME"],
default_keychain: true,
unlock: true,
timeout: 3600,
lock_when_sleeps: true,
password: SecureRandom.base64
)

import_certificate(
certificate_path: "iosDeveloper.p12",
certificate_password: ENV["KEY_PASSWORD"],
keychain_name: ENV["KEYCHAIN_NAME"]
)

import_certificate(
certificate_path: "iosDistribution.p12",
certificate_password: ENV["KEY_PASSWORD"],
keychain_name: ENV["KEYCHAIN_NAME"]
)

sigh(
adhoc: false,
username: ENV["ITUNES_CONNECT_USER"],
cert_id: ENV["TEAM_ID"]
)

set_info_plist_value(
path: './ShipTracked/Info.plist',
key: 'CFBundleVersion',
value: "#{number_of_commits}"
)


gym(
scheme: "ShipTracked",
configuration: "Release",
sdk: "iphoneos9.3",
clean: true,
include_bitcode: false,
include_symbols: true,
use_legacy_build_api: true,
export_method: "app-store"
)

delete_keychain(name: ENV["KEYCHAIN_NAME"])

end

desc "Submit a new beta build to App Store"
lane :beta do

pilot(
username: ENV["ITUNES_CONNECT_USER"],
wait_processing_interval: 30,
distribute_external: false,
skip_submission: true,
skip_waiting_for_build_processing: true,
ipa: "ShipTracked.ipa"
)
end


end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
